f = open('mySocketio.js', 'w+')

f.write("// dependencies\n")
f.write("const socketio = require('socket.io');\n")
f.write("\n")

f.write("// local dependencies\n")
f.write("const ChatRoom = require('./models/chatRoom');\n")
f.write("\n")

f.write("module.exports.socketioListen = function(server) {\n")
f.write("    const io = socketio(server);\n")
f.write("\n")

for i in range(1000):
    namespaceName = 'namespace' + str(i)
    f.write("    const %s = io.of('/%s');\n" % (namespaceName, namespaceName))
    f.write("    %s.on('connection', function(socket) {\n" % namespaceName)
    f.write("        socket.on('chat message', function(msg) {\n")
    f.write("            ChatRoom.findOne({namespace: '/%s'}, function(err, chatRoom) {\n" % namespaceName)
    f.write("                if (err) {\n")
    f.write("                    console.log(\"XXX: Error at ChatRoom.findOne({namespace: '/%s'})\");\n" % namespaceName)
    f.write("                    console.log(err);\n")
    f.write("                    return;\n")
    f.write("                }\n")
    f.write("                if (!chatRoom) {\n")
    f.write("                    chatRoom = new ChatRoom({\n")
    f.write("                        namespace   : '/%s',\n" % namespaceName)
    f.write("                        messages    : []\n")
    f.write("                    });\n")
    f.write("                }\n")
    f.write("                chatRoom.messages.push(msg);\n")
    f.write("                chatRoom.save(function(err) {\n")
    f.write("                    if (err) {\n")
    f.write("                        console.log(\"XXX: Error at ChatRoom.findOne({namespace: '/%s'})->chatRoom.save()\");\n" % namespaceName)
    f.write("                        console.log(err);\n")
    f.write("                        return;\n")
    f.write("                    }\n")
    f.write("                    // If message was saved to database, emit to all clients subscribed to namespace\n")
    f.write("                    %s.emit('chat message', msg);\n" % namespaceName)
    f.write("                });\n")
    f.write("            });\n")
    f.write("        });\n")
    f.write("    });\n")
    f.write("\n")

f.write("}\n")
